# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
        include:
            - os: macos-latest
              python-version: "3.11"
            - os: windows-latest
              python-version: "3.11"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${% raw %}{{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v5
      with:
        python-version: ${% raw %}{{ matrix.python-version }}{% endraw %}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Lint with pylint
      run: |
        pylint metasyncontrib/{{ cookiecutter.__package_name }}
    - name: Check docstrings with pydocstyle
      run: |
        pydocstyle metasyncontrib/{{ cookiecutter.__package_name }} --convention=numpy --add-select=D417 --add-ignore="D102,D105"
    - name: Check types with MyPy
      run: |
        mypy metasyncontrib/{{ cookiecutter.__package_name }}
    - name: Test with pytest
      run: |
        pytest tests
    - name: Check notebook output
      run: |
        pytest --nbval-lax examples
